export interface BoatListing {
  id: string;
  type: "motor" | "sailing" | "catamaran" | "yacht" | "luxury" | "party";
  location: string;
  rating: number;
  reviewCount: number;
  title: string;
  images: string[];
  tags: { label: string; icon: "skipper" | "no-skipper" | "boat-type" | "super-owner" | "no-licence" }[];
  specs: string;
  perks: ("fuel" | "free-cancel" | "flexible-cancel")[];
  price: number;
  priceUnit: string;
  instantBooking: boolean;
  discountOffer: boolean;
  isNew: boolean;
  // Filterable fields
  capacity: number;
  cabins: number;
  berths: number;
  length: number;       // meters
  enginePower: number;  // hp
  year: number;
  superOwner: boolean;
  idealFor: string[];
  equipment: string[];
}

export const trendingBoats: BoatListing[] = [
  {
    id: "t1",
    type: "motor",
    location: "Agios Sostis Harbour, Zakynthos",
    rating: 4.9,
    reviewCount: 163,
    title: "3in1 half Day Cruise – Discover the Beautiful Coast",
    images: [
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Super owner", icon: "super-owner" },
      { label: "Motorboat", icon: "boat-type" },
    ],
    specs: "3 hours · For groups of up to 8 people",
    perks: ["fuel", "free-cancel"],
    price: 375,
    priceUnit: "",
    instantBooking: true,
    discountOffer: false,
    isNew: false,
    capacity: 8,
    cabins: 0,
    berths: 0,
    length: 7,
    enginePower: 150,
    year: 2021,
    superOwner: true,
    idealFor: ["Water-based activities", "Unique experience"],
    equipment: ["External speakers"],
  },
  {
    id: "t2",
    type: "sailing",
    location: "Lefkada Marina, Lefkada",
    rating: 4.8,
    reviewCount: 97,
    title: "Bavaria 46 Cruiser – Premium Sailing Experience",
    images: [
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Sailboat", icon: "boat-type" },
    ],
    specs: "Full day · Up to 10 people",
    perks: ["free-cancel"],
    price: 520,
    priceUnit: "/ day",
    instantBooking: false,
    discountOffer: true,
    isNew: false,
    capacity: 10,
    cabins: 4,
    berths: 8,
    length: 14,
    enginePower: 55,
    year: 2018,
    superOwner: false,
    idealFor: ["Unique experience"],
    equipment: ["Paddle board", "External speakers"],
  },
  {
    id: "t3",
    type: "catamaran",
    location: "Alimos Marina, Athens",
    rating: 5.0,
    reviewCount: 42,
    title: "Lagoon 42 – Luxury Catamaran Week Charter",
    images: [
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Super owner", icon: "super-owner" },
      { label: "Catamaran", icon: "boat-type" },
    ],
    specs: "Weekly · Up to 12 people",
    perks: ["fuel", "free-cancel", "flexible-cancel"],
    price: 1100,
    priceUnit: "/ day",
    instantBooking: true,
    discountOffer: false,
    isNew: true,
    capacity: 12,
    cabins: 4,
    berths: 8,
    length: 13,
    enginePower: 80,
    year: 2023,
    superOwner: true,
    idealFor: ["Unique experience", "Events"],
    equipment: ["Paddle board", "Watermaker", "Generator", "Air Conditioning", "External speakers"],
  },
];

export const allBoats: BoatListing[] = [
  {
    id: "a1",
    type: "motor",
    location: "Old Port, Mykonos",
    rating: 4.7,
    reviewCount: 85,
    title: "Axopar 28 – Speedy Day Trip Around the Island",
    images: [
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "No licence needed", icon: "no-licence" },
      { label: "Motorboat", icon: "boat-type" },
    ],
    specs: "Full day · Up to 6 people",
    perks: ["fuel"],
    price: 450,
    priceUnit: "/ day",
    instantBooking: true,
    discountOffer: false,
    isNew: false,
    capacity: 6,
    cabins: 0,
    berths: 0,
    length: 8,
    enginePower: 300,
    year: 2022,
    superOwner: false,
    idealFor: ["Wakeboard and water skis", "Water-based activities"],
    equipment: ["Wakeboard", "Towable Tube", "External speakers"],
  },
  {
    id: "a2",
    type: "yacht",
    location: "Flisvos Marina, Athens",
    rating: 4.6,
    reviewCount: 31,
    title: "Princess V50 – Luxury Yacht for Unforgettable Evenings",
    images: [
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Super owner", icon: "super-owner" },
      { label: "Yacht", icon: "boat-type" },
    ],
    specs: "Full day · Up to 10 people",
    perks: ["fuel", "flexible-cancel"],
    price: 980,
    priceUnit: "/ day",
    instantBooking: false,
    discountOffer: true,
    isNew: false,
    capacity: 10,
    cabins: 2,
    berths: 4,
    length: 15,
    enginePower: 400,
    year: 2020,
    superOwner: true,
    idealFor: ["Events", "Unique experience"],
    equipment: ["Generator", "Air Conditioning", "External speakers", "Watermaker"],
  },
  {
    id: "a3",
    type: "sailing",
    location: "Corfu Marina, Corfu",
    rating: 4.4,
    reviewCount: 56,
    title: "Jeanneau Sun Odyssey 440 – Explore the Ionian Sea",
    images: [
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Without skipper", icon: "no-skipper" },
      { label: "Sailboat", icon: "boat-type" },
    ],
    specs: "Weekly · Up to 8 people",
    perks: ["free-cancel"],
    price: 350,
    priceUnit: "/ day",
    instantBooking: true,
    discountOffer: false,
    isNew: false,
    capacity: 8,
    cabins: 3,
    berths: 6,
    length: 13,
    enginePower: 45,
    year: 2019,
    superOwner: false,
    idealFor: ["Unique experience"],
    equipment: ["Paddle board"],
  },
  {
    id: "a4",
    type: "party",
    location: "Piraeus, Athens",
    rating: 4.8,
    reviewCount: 122,
    title: "Party Boat Deluxe – DJ, Bar & Swimming Platform",
    images: [
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Super owner", icon: "super-owner" },
      { label: "Motorboat", icon: "boat-type" },
    ],
    specs: "4 hours · Up to 20 people",
    perks: ["fuel", "free-cancel"],
    price: 750,
    priceUnit: "",
    instantBooking: true,
    discountOffer: false,
    isNew: true,
    capacity: 20,
    cabins: 1,
    berths: 2,
    length: 12,
    enginePower: 250,
    year: 2024,
    superOwner: true,
    idealFor: ["Events", "Water-based activities"],
    equipment: ["External speakers", "Towable Tube", "Paddle board"],
  },
  {
    id: "a5",
    type: "motor",
    location: "Naxos Port, Naxos",
    rating: 3.9,
    reviewCount: 14,
    title: "Small Motorboat – Budget-Friendly Island Hopping",
    images: [
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "No licence needed", icon: "no-licence" },
      { label: "Motorboat", icon: "boat-type" },
    ],
    specs: "Full day · Up to 4 people",
    perks: ["fuel"],
    price: 120,
    priceUnit: "/ day",
    instantBooking: true,
    discountOffer: false,
    isNew: false,
    capacity: 4,
    cabins: 0,
    berths: 0,
    length: 5,
    enginePower: 30,
    year: 2016,
    superOwner: false,
    idealFor: ["Fishing"],
    equipment: [],
  },
  {
    id: "a6",
    type: "luxury",
    location: "Elounda, Crete",
    rating: 5.0,
    reviewCount: 28,
    title: "Sunseeker 75 – Ultra-Luxury Cruise with Crew",
    images: [
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Super owner", icon: "super-owner" },
      { label: "Yacht", icon: "boat-type" },
    ],
    specs: "Full day · Up to 12 people",
    perks: ["fuel", "free-cancel", "flexible-cancel"],
    price: 1200,
    priceUnit: "/ day",
    instantBooking: false,
    discountOffer: true,
    isNew: false,
    capacity: 12,
    cabins: 4,
    berths: 8,
    length: 15,
    enginePower: 400,
    year: 2025,
    superOwner: true,
    idealFor: ["Events", "Unique experience"],
    equipment: ["Watermaker", "Generator", "Air Conditioning", "External speakers", "Paddle board", "Towable Tube"],
  },
  {
    id: "a7",
    type: "catamaran",
    location: "Kos Marina, Kos",
    rating: 4.3,
    reviewCount: 67,
    title: "Bali 4.0 – Spacious Catamaran for Family Holidays",
    images: [
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Without skipper", icon: "no-skipper" },
      { label: "Catamaran", icon: "boat-type" },
    ],
    specs: "Weekly · Up to 10 people",
    perks: ["flexible-cancel"],
    price: 680,
    priceUnit: "/ day",
    instantBooking: false,
    discountOffer: false,
    isNew: false,
    capacity: 10,
    cabins: 4,
    berths: 8,
    length: 12,
    enginePower: 60,
    year: 2017,
    superOwner: false,
    idealFor: ["Unique experience"],
    equipment: ["Paddle board", "Generator"],
  },
  {
    id: "a8",
    type: "motor",
    location: "Santorini Port, Santorini",
    rating: 4.5,
    reviewCount: 203,
    title: "Speed Rib 7.5m – Caldera Sunset Tour",
    images: [
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Motorboat", icon: "boat-type" },
    ],
    specs: "5 hours · Up to 8 people",
    perks: ["fuel", "free-cancel"],
    price: 290,
    priceUnit: "",
    instantBooking: true,
    discountOffer: false,
    isNew: false,
    capacity: 8,
    cabins: 0,
    berths: 0,
    length: 7,
    enginePower: 200,
    year: 2020,
    superOwner: false,
    idealFor: ["Water-based activities", "Unique experience"],
    equipment: ["External speakers"],
  },
  {
    id: "a9",
    type: "sailing",
    location: "Thessaloniki Marina",
    rating: 4.1,
    reviewCount: 19,
    title: "Hanse 385 – Affordable Sailing in the Aegean",
    images: [
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Without skipper", icon: "no-skipper" },
      { label: "Sailboat", icon: "boat-type" },
    ],
    specs: "Weekly · Up to 6 people",
    perks: [],
    price: 220,
    priceUnit: "/ day",
    instantBooking: false,
    discountOffer: false,
    isNew: false,
    capacity: 6,
    cabins: 3,
    berths: 6,
    length: 12,
    enginePower: 40,
    year: 2012,
    superOwner: false,
    idealFor: ["Fishing"],
    equipment: [],
  },
  {
    id: "a10",
    type: "yacht",
    location: "Rhodes Marina, Rhodes",
    rating: 4.9,
    reviewCount: 78,
    title: "Azimut 55 – Premium Yacht with Full Crew",
    images: [
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Super owner", icon: "super-owner" },
      { label: "Yacht", icon: "boat-type" },
    ],
    specs: "Full day · Up to 10 people",
    perks: ["fuel", "free-cancel"],
    price: 890,
    priceUnit: "/ day",
    instantBooking: true,
    discountOffer: false,
    isNew: true,
    capacity: 10,
    cabins: 3,
    berths: 6,
    length: 14,
    enginePower: 350,
    year: 2023,
    superOwner: true,
    idealFor: ["Events", "Unique experience"],
    equipment: ["Air Conditioning", "Generator", "Watermaker", "External speakers", "Paddle board"],
  },
  {
    id: "a11",
    type: "motor",
    location: "Paros Port, Paros",
    rating: 4.2,
    reviewCount: 45,
    title: "Quicksilver 675 – Fun Day on the Water",
    images: [
      "https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "No licence needed", icon: "no-licence" },
      { label: "Motorboat", icon: "boat-type" },
    ],
    specs: "Full day · Up to 7 people",
    perks: ["fuel", "flexible-cancel"],
    price: 280,
    priceUnit: "/ day",
    instantBooking: true,
    discountOffer: false,
    isNew: false,
    capacity: 7,
    cabins: 0,
    berths: 0,
    length: 6,
    enginePower: 150,
    year: 2021,
    superOwner: false,
    idealFor: ["Wakeboard and water skis", "Water-based activities", "Fishing"],
    equipment: ["Wakeboard", "Towable Tube"],
  },
  {
    id: "a12",
    type: "luxury",
    location: "Vouliagmeni, Athens",
    rating: 4.7,
    reviewCount: 53,
    title: "Pershing 62 – Sleek Italian Luxury on Water",
    images: [
      "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=500&q=80&auto=format",
      "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=500&q=80&auto=format",
    ],
    tags: [
      { label: "Skipper included", icon: "skipper" },
      { label: "Yacht", icon: "boat-type" },
    ],
    specs: "Full day · Up to 8 people",
    perks: ["fuel", "free-cancel"],
    price: 950,
    priceUnit: "/ day",
    instantBooking: false,
    discountOffer: false,
    isNew: false,
    capacity: 8,
    cabins: 2,
    berths: 4,
    length: 14,
    enginePower: 380,
    year: 2022,
    superOwner: false,
    idealFor: ["Events", "Unique experience"],
    equipment: ["Air Conditioning", "Generator", "External speakers"],
  },
];
