import type { Destination, Review, Article } from "../types";

export const mockDestinations: Destination[] = [
  {
    id: "1",
    name: "Ibiza",
    slug: "ibiza",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&q=80&auto=format",
    description: "Party and paradise in the Balearic Islands",
    boatCount: 342,
  },
  {
    id: "2",
    name: "Santorini",
    slug: "santorini",
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600&q=80&auto=format",
    description: "Iconic sunsets and volcanic waters",
    boatCount: 187,
  },
  {
    id: "3",
    name: "Dubrovnik",
    slug: "dubrovnik",
    image: "https://images.unsplash.com/photo-1555990538-1e6c53b44ce5?w=600&q=80&auto=format",
    description: "Crystal clear Adriatic coastline",
    boatCount: 156,
  },
  {
    id: "4",
    name: "Amalfi Coast",
    slug: "amalfi-coast",
    image: "https://images.unsplash.com/photo-1534008897995-27a23e859048?w=600&q=80&auto=format",
    description: "Italian coastal paradise",
    boatCount: 234,
  },
  {
    id: "5",
    name: "Mykonos",
    slug: "mykonos",
    image: "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=600&q=80&auto=format",
    description: "Windmills and turquoise waters",
    boatCount: 198,
  },
  {
    id: "6",
    name: "Côte d'Azur",
    slug: "cote-d-azur",
    image: "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=600&q=80&auto=format",
    description: "The glamorous French Riviera",
    boatCount: 276,
  },
  {
    id: "7",
    name: "Sardinia",
    slug: "sardinia",
    image: "https://images.unsplash.com/photo-1586105449897-20b5efeb3233?w=600&q=80&auto=format",
    description: "Hidden coves and emerald seas",
    boatCount: 145,
  },
  {
    id: "8",
    name: "Split",
    slug: "split",
    image: "https://images.unsplash.com/photo-1592150621744-aca64f48394a?w=600&q=80&auto=format",
    description: "Gateway to Croatian islands",
    boatCount: 213,
  },
];

export const mockReviews: Review[] = [
  {
    id: "1",
    boatId: "b1",
    userId: "u1",
    userName: "Maria Santos",
    rating: 5,
    comment: "Absolutely incredible experience! The boat was in perfect condition and the skipper was so knowledgeable about the best spots.",
    boatName: "Sea Breeze 42",
    location: "Ibiza, Spain",
    createdAt: new Date("2025-09-15"),
  },
  {
    id: "2",
    boatId: "b2",
    userId: "u2",
    userName: "James Wilson",
    rating: 5,
    comment: "Best family holiday we've ever had. The kids loved it and the booking process was seamless.",
    boatName: "Ocean Dream",
    location: "Santorini, Greece",
    createdAt: new Date("2025-08-22"),
  },
  {
    id: "3",
    boatId: "b3",
    userId: "u3",
    userName: "Sophie Laurent",
    rating: 4,
    comment: "Beautiful catamaran, well-maintained. The only thing was pickup was a bit late, but otherwise perfect.",
    boatName: "Cat Paradise",
    location: "Côte d'Azur, France",
    createdAt: new Date("2025-10-01"),
  },
  {
    id: "4",
    boatId: "b4",
    userId: "u4",
    userName: "Marco Rossi",
    rating: 5,
    comment: "We sailed along the Amalfi coast for 3 days. Unforgettable sunsets and hidden beaches. Highly recommend!",
    boatName: "Bella Vista",
    location: "Amalfi, Italy",
    createdAt: new Date("2025-07-10"),
  },
  {
    id: "5",
    boatId: "b5",
    userId: "u5",
    userName: "Elena Popov",
    rating: 5,
    comment: "Third time booking through BoatHaven. Consistently great service and beautiful boats. My go-to platform.",
    boatName: "Adriatic Star",
    location: "Dubrovnik, Croatia",
    createdAt: new Date("2025-11-05"),
  },
  {
    id: "6",
    boatId: "b6",
    userId: "u6",
    userName: "Tom Anderson",
    rating: 4,
    comment: "Great motor yacht for a day trip. Clean, well-equipped, and the owner was very responsive.",
    boatName: "Speed King",
    location: "Mykonos, Greece",
    createdAt: new Date("2025-08-30"),
  },
];

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "Top 10 Sailing Destinations in the Mediterranean for 2026",
    slug: "top-10-sailing-destinations-mediterranean-2026",
    image: "https://images.unsplash.com/photo-1500514966906-fe245eea9344?w=600&q=80&auto=format",
    summary: "Discover the most breathtaking Mediterranean sailing routes, from hidden Greek coves to the stunning Croatian coastline.",
    content: "",
    createdAt: new Date("2026-02-20"),
  },
  {
    id: "2",
    title: "First-Time Boat Renter? Everything You Need to Know",
    slug: "first-time-boat-renter-guide",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&q=80&auto=format",
    summary: "A comprehensive guide covering licenses, insurance, what to pack, and how to choose the right boat for your experience level.",
    content: "",
    createdAt: new Date("2026-02-10"),
  },
  {
    id: "3",
    title: "Catamaran vs Sailboat: Which One Should You Rent?",
    slug: "catamaran-vs-sailboat-comparison",
    image: "https://images.unsplash.com/photo-1605281317010-fe5ffe798166?w=600&q=80&auto=format",
    summary: "We break down the pros and cons of each to help you choose the perfect vessel for your next sailing adventure.",
    content: "",
    createdAt: new Date("2026-01-28"),
  },
];
